repos:
  - repo: https://github.com/Azure4DevOps/check-azure-bicep
    rev: master
    #rev: v0.2.1 # ${LATEST_SHA_OR_VERSION}
    hooks:
      - id: check-azure-bicep
      - id: check-azure-bicep-python
