          steps:
          - task: DownloadPipelineArtifact@1
            displayName: 'Download Pipeline Artifact'
            inputs:
              buildType: 'current'
          - script: |
              pwd
              echo "Starting deployment script run"
              #curl -T '$(output.directory)/$(artifact.name)' 'https://$(server.dev.user):$(server.dev.password)@$(server.dev.host)/manager/text/deploy?path=/$(artifact.azure.name)&update=true'
              displayName: 'Deploying app'
              cp -rf '$(System.DefaultWorkingDirectory)/$(webappname).zip' '/usr/local/src'

          #- task: AzureWebApp@1
          #  inputs:
          #    #azureSubscription: '$(subscription)'
          #    #azureSubscription: 'korio-platform-dev'
          #    appType: 'webApp'
          #    appName: '$(webappname)'
          #    package: '$(System.DefaultWorkingDirectory)/$(webappname).zip'
          #    #customWebConfig: '-Handler iisnode -NodeStartFile index.js -appType node'
          #    deploymentMethod: 'zipDeploy'
